# Generated by Django 5.2.3 on 2025-06-19 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leagueauction',
            unique_together=set(),
        ),
    ]
