# Generated by Django 5.2.3 on 2025-06-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_leagueround'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamcyclist',
            name='price',
            field=models.IntegerField(),
        ),
    ]
