# Generated by Django 5.2.3 on 2025-06-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_teamcyclist_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='invite_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
