# Generated by Django 5.2.3 on 2025-06-25 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_league_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='members',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
