# Generated by Django 5.2.3 on 2025-06-26 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_league_members_delete_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='app.competition')),
            ],
        ),
        migrations.CreateModel(
            name='StageSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('riders', models.ManyToManyField(related_name='stage_selections', to='app.cyclist')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='app.stage')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_selections', to='app.team')),
            ],
            options={
                'unique_together': {('team', 'stage')},
            },
        ),
    ]
