# Generated by Django 5.2.3 on 2025-06-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_stage_stageselection'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stageselection',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='stageselection',
            name='validated',
            field=models.BooleanField(default=False, help_text='Is this the last valid selection before lock?'),
        ),
    ]
