# Generated by Django 5.2.3 on 2025-06-26 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_stageselection_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stageselection',
            name='grimpeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.cyclist'),
        ),
        migrations.AddField(
            model_name='stageselection',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.cyclist'),
        ),
        migrations.AddField(
            model_name='stageselection',
            name='sprinteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.cyclist'),
        ),
        migrations.CreateModel(
            name='BonusConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_per_player', models.PositiveIntegerField(default=1)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_configs', to='app.competition')),
            ],
        ),
        migrations.CreateModel(
            name='StageSelectionBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1)),
                ('bonus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bonusconfig')),
                ('stage_selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stageselection')),
            ],
            options={
                'unique_together': {('stage_selection', 'bonus')},
            },
        ),
        migrations.AddField(
            model_name='stageselection',
            name='bonuses',
            field=models.ManyToManyField(blank=True, related_name='stage_selections', through='app.StageSelectionBonus', to='app.bonusconfig'),
        ),
    ]
