# Generated by Django 5.2.3 on 2025-06-26 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_stageselection_grimpeur_stageselection_leader_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='stageselection',
            name='grimpeur',
        ),
        migrations.RemoveField(
            model_name='stageselection',
            name='leader',
        ),
        migrations.RemoveField(
            model_name='stageselection',
            name='riders',
        ),
        migrations.RemoveField(
            model_name='stageselection',
            name='sprinteur',
        ),
        migrations.CreateModel(
            name='StageSelectionRider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cyclist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cyclist')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.role')),
                ('stage_selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selection_riders', to='app.stageselection')),
            ],
            options={
                'unique_together': {('stage_selection', 'cyclist')},
            },
        ),
    ]
