# Generated by Django 5.2.3 on 2025-06-27 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_role_remove_stageselection_grimpeur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionCyclistConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cyclist_confirmations', to='app.competition')),
                ('cyclist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_confirmations', to='app.cyclist')),
            ],
            options={
                'unique_together': {('competition', 'cyclist')},
            },
        ),
    ]
