# Generated by Django 5.2.3 on 2025-06-27 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_competitioncyclistconfirmation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cyclist',
            name='nationality',
        ),
    ]
