# Generated by Django 5.2.3 on 2025-06-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_cyclist_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='auction_finished',
            field=models.BooleanField(blank=True, default=None, help_text='True si les enchères sont terminées, NULL sinon.', null=True),
        ),
    ]
