# Generated by Django 5.2.3 on 2025-07-04 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_league_auction_finished'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultStageSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_stage_selections', to='app.team')),
            ],
        ),
        migrations.CreateModel(
            name='DefaultStageSelectionRider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cyclist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cyclist')),
                ('default_selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riders', to='app.defaultstageselection')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.role')),
            ],
            options={
                'unique_together': {('default_selection', 'cyclist')},
            },
        ),
    ]
