# Generated by Django 5.2.3 on 2025-07-04 16:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_defaultstageselection_defaultstageselectionrider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_batch_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('rnk', models.CharField(blank=True, max_length=10, null=True)),
                ('gc', models.CharField(blank=True, max_length=10, null=True)),
                ('timelag', models.CharField(blank=True, max_length=20, null=True)),
                ('bib', models.CharField(blank=True, max_length=10, null=True)),
                ('h2h', models.CharField(blank=True, max_length=10, null=True)),
                ('specialty', models.CharField(blank=True, max_length=50, null=True)),
                ('rider', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.CharField(blank=True, max_length=10, null=True)),
                ('team', models.CharField(blank=True, max_length=255, null=True)),
                ('uci', models.CharField(blank=True, max_length=20, null=True)),
                ('pnt', models.CharField(blank=True, max_length=10, null=True)),
                ('time', models.CharField(blank=True, max_length=20, null=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='app.stage')),
            ],
        ),
    ]
