# Generated by Django 5.2.3 on 2025-07-04 17:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_resultat'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishPointsResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_batch_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('rnk', models.IntegerField(blank=True, null=True)),
                ('bib', models.IntegerField(blank=True, null=True)),
                ('h2h', models.BooleanField(blank=True, null=True)),
                ('specialty', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('rider', models.CharField(blank=True, max_length=255, null=True)),
                ('team', models.CharField(blank=True, max_length=255, null=True)),
                ('pnt', models.IntegerField(blank=True, null=True)),
                ('bonis', models.CharField(blank=True, max_length=20, null=True)),
                ('today', models.CharField(blank=True, max_length=20, null=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finish_points_results', to='app.stage')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_batch_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('rnk', models.IntegerField(blank=True, null=True)),
                ('bib', models.IntegerField(blank=True, null=True)),
                ('h2h', models.BooleanField(blank=True, null=True)),
                ('specialty', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('rider', models.CharField(blank=True, max_length=255, null=True)),
                ('team', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.CharField(blank=True, max_length=20, null=True)),
                ('time_wonlost', models.CharField(blank=True, max_length=20, null=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_results', to='app.stage')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralTimeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_batch_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('rnk', models.IntegerField(blank=True, null=True)),
                ('bib', models.IntegerField(blank=True, null=True)),
                ('h2h', models.BooleanField(blank=True, null=True)),
                ('specialty', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('rider', models.CharField(blank=True, max_length=255, null=True)),
                ('team', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.CharField(blank=True, max_length=20, null=True)),
                ('time_wonlost', models.CharField(blank=True, max_length=20, null=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_time_results', to='app.stage')),
            ],
        ),
        migrations.CreateModel(
            name='KOMResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_batch_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('rnk', models.IntegerField(blank=True, null=True)),
                ('bib', models.IntegerField(blank=True, null=True)),
                ('h2h', models.BooleanField(blank=True, null=True)),
                ('specialty', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('rider', models.CharField(blank=True, max_length=255, null=True)),
                ('team', models.CharField(blank=True, max_length=255, null=True)),
                ('pnt', models.IntegerField(blank=True, null=True)),
                ('today', models.CharField(blank=True, max_length=20, null=True)),
                ('kom_type', models.CharField(blank=True, max_length=100, null=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kom_results', to='app.stage')),
            ],
        ),
        migrations.CreateModel(
            name='PointsResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_batch_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('rnk', models.IntegerField(blank=True, null=True)),
                ('bib', models.IntegerField(blank=True, null=True)),
                ('h2h', models.BooleanField(blank=True, null=True)),
                ('specialty', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('rider', models.CharField(blank=True, max_length=255, null=True)),
                ('team', models.CharField(blank=True, max_length=255, null=True)),
                ('pnt', models.IntegerField(blank=True, null=True)),
                ('today', models.CharField(blank=True, max_length=20, null=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_results', to='app.stage')),
            ],
        ),
        migrations.CreateModel(
            name='YouthResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_batch_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('rnk', models.IntegerField(blank=True, null=True)),
                ('bib', models.IntegerField(blank=True, null=True)),
                ('h2h', models.BooleanField(blank=True, null=True)),
                ('specialty', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('rider', models.CharField(blank=True, max_length=255, null=True)),
                ('team', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.CharField(blank=True, max_length=20, null=True)),
                ('time_wonlost', models.CharField(blank=True, max_length=20, null=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youth_results', to='app.stage')),
            ],
        ),
    ]
