# Generated by Django 5.2.3 on 2025-07-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_finishpointsresult_generalresult_generaltimeresult_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalresult',
            name='time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='generalresult',
            name='time_wonlost',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='generaltimeresult',
            name='time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='generaltimeresult',
            name='time_wonlost',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='youthresult',
            name='time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='youthresult',
            name='time_wonlost',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
